insta/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('posts.urls')),
    path('', include('myapi.routers')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models

# Create your models here.
from accounts.models import PublicUser
class Post(models.Model):
    # user =<ob1>
    #user_id =1
    user=models.ForeignKey(PublicUser, on_delete=models.CASCADE, related_name="post_user")
    image =models.ImageField(upload_to="uploads/posts",default="p.png")
    desc =models.TextField(max_length=1000)
    post_type = models.CharField(max_length=1,
                              choices=(('1', "Public"), ('2', "Private")),
                              default="1")
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at =models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1,
                                 choices=(
                                     ('1', "Active"),
                                     ('2', "Inactive"),
                                     ('3', "Blocked"),
                                     ('4', "Spam"),
                                 ),
                                 default="1")
    likes =models.ManyToManyField(PublicUser, related_name="like_post",null=True,blank=True)





    # likes=[1,2,5,5]
    # class like_post():
    #     user =models.ForeignKey(PublicUser, on_delete=models.CASCADE, related_name="post_user")
    #     post =models.ForeignKey(Post, on_delete=models.CASCADE, related_name="post_user")
# user=PublicUser.objects.get(id=2)
# user.like_post.filter()


class Comment(models.Model):
    user=models.ForeignKey(PublicUser, on_delete=models.CASCADE, related_name="comment_user")
    post =models.ForeignKey(Post, on_delete=models.CharField, related_name='comment_post')
    comment=models.CharField(max_length=2000)
    created_at =models.DateTimeField(auto_now=True)
    status =models.BooleanField(default=True)


# table=commnet
# user_id =5
# post_id =1
# created_at=date(22/-2021)
# status=1


"""
Database Relationship in tables (maltipal table)
one-to-one  dublicate entry not accepted
one-to-many dublicate entry accepted but only one entry at a time
many to many dublicate entry not accepted but matlipal eny posible

how to make relation in table


primarykey=unique key
ForeignKey=reapeat value accecpt


join()
inner join
outer join
cross
self

"""

class Follow(models.Model):
    user = models.ForeignKey(PublicUser, on_delete=models.CASCADE, related_name="followers")
    follow_user = models.ForeignKey(PublicUser, on_delete=models.CASCADE, related_name="following")
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "friends"

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Arvo:wght@400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <title>{% block title%} {% endblock%}</title>
  <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
{% block content%}
{% endblock%}

<script>
    function loadPost(){
        $("#allPosts").load("/all_posts/")
    }
     function loadFollowList(user_id){
        $("#follow_list").load("/follow_list/")
    }

    loadPost();
    loadFollowList();


   $('#addPostForm').submit(function(e){
        e.preventDefault();
        //var image =$("#id_image").val();
        //var desc =$("#id_desc").val();
        //console.log(image);
        //console.log(desc);

       var formData = new FormData(this);

       $.ajax({
            url:"/addPost/",
            data:formData,
            type:"post",
            contentType: false,
            processData: false,
            success:function(data){
            $("#msg").html(data);
            loadPost();
             $('#AddPostModal').modal('toggle');


            }
       });

   });

</script>
<script>
    function likePost(post_id){
        $.ajax({
            url:"/post_like/"+post_id+"/",
            success:function(data){
                $("#like_icon"+post_id).addClass("text-dark");
                 loadPost();
            }
        });
    }

    function followUser(user_id){

        $.ajax({
            url:"/follow_unfollow/"+user_id+"/",
            success:function(data){
               console.log(data);
               loadFollowList();
            }
        });
    }
</script>
<script>
  $(window).scroll(function(){
    if ($(window).scrollTop() == $(document).height() - $(window).height()){
      console.log("ok");
    }
    });
</script>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
thos is my api
</body>
</html>

templates/index.html
{% extends 'base.html'%}
{% block content%}



{% include 'nav.html'%}

<div class="container">
    <div class="row">
        <div class="col-md-5">
            <div class="py-5" id="allPosts">
            </div>
        </div>
        <div class="col-md-5">
            <div class="my-1">
                <h4 class="py-2">Follow Friends</h4>
                <ul class="list list-inline bg-light p-4 follower-list" id="follow_list">
                </ul>
            </div>

        </div>
    </div>



</div>




{% endblock %}

templates/nav.html
<div class="modal" id="AddPostModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">New Post</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
          <div id="msg">................</div>
        <form method="post" id="addPostForm" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <input type="file" name="image" id="id_image" required>
            </div>
            <div class="form-group">
                <textarea class="form-control" name="desc" id="id_desc" required></textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Save Post</button>
            </div>
        </form>
      </div>

    </div>
  </div>
</div>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">

  <a class="navbar-brand" href="/">My Insta</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/accounts/profile/{{request.user.id}}/">Profile<span class="sr-only">(current)</span></a>
      </li>

        <li class="nav-item">
        <a class="nav-link" href="#" data-toggle="modal" data-target="#AddPostModal"> + Add Post</a>
      </li>

    </ul>
    <div class="form-inline my-2 my-lg-0">
        <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         {{request.user.myusername}}
            <img src="/media/{{request.user.image}}" width="20px">
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Profile</a>
          <a class="dropdown-item" href="#">Setting</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item text-danger" href="{% url 'logout' %}">Logout</a>
        </div>
      </div>
      </div>
  </div>
</div>
</nav>